### ISSUE TITLE
Thoughts on supporting additional regex flavors?

### ISSUE THREAD

**Issue by slevithan** [fabiospampinato/grepgrep#1]
[Regex+](https://github.com/slevithan/regex) supports a strict superset of native JS `RegExp`-with-flag-`v` syntax, adding several useful features (free spacing, atomic groups, possessive quantifiers, subroutines, etc.).

Oniguruma (via [Oniguruma-To-ES](https://github.com/slevithan/oniguruma-to-es)) is also possible but I wouldn't necessarily recommend it for this case because Oniguruma syntax/behavior is very different from JS, there are edge-case-support issues to be aware of, and the library is significantly bigger than Regex+.

**Comment by fabiospampinato** [comment]
Thanks for the suggestion, but generally I try not to pull in third-party dependencies unless they are necessary, and I think supporting other regex flavors is not necessary for this package.

I think it could make sense to support Regex+ in a forked version of this package though, "grepgrep+" or "ggp" sounds like a good name for it.

**Comment by fabiospampinato** [comment]
It might be interesting to somehow get the regex from stdin also, so that this package could be kinda chained with another one that converts regex+ regexes to regular regexes (what a tongue twister 🤣), so that one doesn't need to fork the whole thing. 

Would you like something like that?

**Comment by slevithan** [comment]
It's an interesting idea. I'm not currently using `grepgrep` so this is more just an idea if you think it would improve DX. The DX benefits would be greater if e.g. a series of regexes could be stored/loaded from a file--then readability/maintainability of regexes would become more valuable, and Regex+'s extended features would make a bigger difference.

**Comment by fabiospampinato** [comment]
Let's track this in #2, as built-in support for other flavors doesn't fit the program I think.
